redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\fair_ride\\comparify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions.api]
timeout = 26.0

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "C:\\fair_ride\\comparify\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\fair_ride\\comparify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api"
to = "/.netlify/functions/api"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]